### ISSUE TITLE
Music & Sound Not Working

### ISSUE THREAD

**Issue by msmigiel** [sandstranger/Underworld-Exporter-Android#2]
I am running version Underworld Exporter version 1.3.1 on a Samsung Tab S5e, which is running Android version 11.

When I start up the application pointing to Ultima Underworld 1, there is no music or sound, despite being enabled in the game settings.  One other oddity is that in the Sound menu, the options seemed to be reversed. For example, if I go to Options -> Sound and click "ON", it turns off, and vice versa. The Music menu does not have this problem.

**Comment by sandstranger** [comment]
Music is not included in binary file.
You need to download it from here https://www.nexusmods.com/ultimaunderworldunity/mods/1
then copy this music to your phone,
and write path to it in config.ini, which is stored in game folder.
https://github.com/sandstranger/Underworld-Exporter-Android/blob/android/Assets/StreamingAssets/Configs/config.ini#L49

**Comment by msmigiel** [comment]
Thank you, I will try that. Where is this file stored in the Android file system?

Might I make some suggestions too?
- It might be good to document this in the readme.
- It would be nice to have this as a setting in the first config screen (where the game paths are chosen).
- Is there a similar one for Ultima Underworld 2?

**Comment by sandstranger** [comment]
The config is stored in the folder where all game data files are stored.
![Screenshot_20241124_214906](https://github.com/user-attachments/assets/8dc6dce1-788a-4789-af97-fd8879749dc9)
![Screenshot_20241124_214852_com UnderworldExporter UnderworldExporter](https://github.com/user-attachments/assets/4de832c4-46dd-490f-ad34-0b61924a558c)

**Comment by sandstranger** [comment]
You can download music for ultima underworld 2 here.
https://github.com/hankmorgan/UnderworldExporter/releases/download/v1.10/MusicPack.zip
All sound issues must be fixed in this build
You can also change path to music folder in this build.
https://github.com/sandstranger/Underworld-Exporter-Android/releases/tag/1.3.2
