### ISSUE TITLE
Ability to set movement and cursor sensitivity

### ISSUE THREAD

**Issue by msmigiel** [sandstranger/Underworld-Exporter-Android#22]
It would be a nice addition to set the sensitivity of the movement speed as well as the mouse cursor. Personally, I find the movement speed nice but in mouse cursor mode, the cursor moves too slow. It would be nice to able to adjust these independently.

**Comment by sandstranger** [comment]
You can change cursor sensitivity for gamepad in settings 
![Screenshot_20241203-005001](https://github.com/user-attachments/assets/e387a797-faf8-4a79-aa84-16e5cbde38c1)

**Comment by sandstranger** [comment]
ajust changing player speed is done in last commit
https://github.com/sandstranger/Underworld-Exporter-Android/commit/e6d9570ab7740db41b8d4c61d9f73ee77678f543
