### ISSUE TITLE
Ability to change swim speed

### ISSUE THREAD

**Issue by msmigiel** [sandstranger/Underworld-Exporter-Android#30]
In the config menu, there is an option to control player speed. This is a nice touch and makes the game feel more responsive. Please consider adding a separate option to control swim speed. Swimming is very slow and would be nice to control independently from walking speed.

**Comment by mickromash** [comment]
Swimming actually supposed to be that slow. There's a spell that allows walking on the water and a swimming skill (not sure how helpful it is tho)
